name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for commitizen check

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"

    - name: Run pre-commit
      run: |
        pre-commit run --all-files

    - name: Test with pytest
      run: |
        pytest --cov=nemdatatools --cov-report=xml

    - name: Check commit messages (on pull request)
      if: github.event_name == 'pull_request'
      run: |
        cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install UV
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv pip install -e ".[docs]"

    - name: Build documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html

    - name: Archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html
